/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import dao.CidadesDAO;
import dao.ClientesDAO;
import dao.UfDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javabeans.Cidades;
import javabeans.Clientes;
import javabeans.Uf;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte
 */
public class Cidade extends javax.swing.JDialog {
    CidadesDAO dao;
    /**
     * Creates new form Cidade
     */
    public Cidade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cidade dialog = new Cidade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuf = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        btnovo = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelacidade = new javax.swing.JTable();
        btatualizar = new javax.swing.JButton();
        cbouf = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cidade");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtuf.setEditable(false);
        txtuf.setBorder(javax.swing.BorderFactory.createTitledBorder("UF"));

        txtcodigo.setEditable(false);
        txtcodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));

        txtnome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        tabelacidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "UF"
            }
        ));
        tabelacidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelacidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelacidade);

        btatualizar.setText("Atualizar");
        btatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btatualizarActionPerformed(evt);
            }
        });

        cbouf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Estado" }));
        cbouf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboufItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btsalvar))
                            .addComponent(btatualizar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbouf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtuf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbouf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnovo)
                            .addComponent(btsalvar))
                        .addGap(8, 8, 8)
                        .addComponent(btatualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        Novo();
    }//GEN-LAST:event_btnovoActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        Salvar();
    }//GEN-LAST:event_btsalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
        try{
            
            UfDAO dao_t = new UfDAO();
            List<Uf> lista = dao_t.listarEstados();
            for(Uf u:lista){
                cbouf.addItem(u.getSigla());
            }
                    
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_formWindowActivated

    private void tabelacidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelacidadeMouseClicked
        txtcodigo.setText(tabelacidade.getValueAt(tabelacidade.getSelectedRow(),0).toString());
        txtnome.setText(tabelacidade.getValueAt(tabelacidade.getSelectedRow(),1).toString());
        txtuf.setText(tabelacidade.getValueAt(tabelacidade.getSelectedRow(),2).toString());
    }//GEN-LAST:event_tabelacidadeMouseClicked

    private void btatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btatualizarActionPerformed
        Atualizar();
    }//GEN-LAST:event_btatualizarActionPerformed

    private void cboufItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboufItemStateChanged
        if(cbouf.getSelectedItem().toString() != cbouf.getItemAt(0)){
            CidadesDAO cidade = new CidadesDAO();

            try{
                txtuf.setText(String.valueOf(cidade.getCidade(cbouf.getSelectedItem().toString())));
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_cboufItemStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btatualizar;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btsalvar;
    private javax.swing.JComboBox<String> cbouf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelacidade;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables

    void Novo(){
        txtcodigo.setText(null);
        txtnome.setText(null);
        txtuf.setText(null);
        txtnome.requestFocus();
    }
    void Salvar(){
        try{
            UfDAO temp = new UfDAO();
            
            Cidades obj = new Cidades();
            obj.setNome(txtnome.getText());
            obj.setUf(temp.buscarEstado(cbouf.getSelectedItem().toString()));
            
            dao = new CidadesDAO();
            dao.cadastrarCidade(obj);
            
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar a cidade");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Listar(){
        try{
            CidadesDAO dao = new CidadesDAO();
            List<Cidades> listarcidades = dao.listarCidades();
            DefaultTableModel modelo = (DefaultTableModel) tabelacidade.getModel();
            modelo.setNumRows(0);
            
            for(Cidades lc : listarcidades){
                
                modelo.addRow(new Object[]{
                        lc.getId(),
                        lc.getNome(),
                        lc.getUf()
                        });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    void Atualizar(){
        try{
            UfDAO temp = new UfDAO();
            Cidades obj = new Cidades();
            obj.setNome(txtnome.getText());
            obj.setUf(temp.buscarEstado(cbouf.getSelectedItem().toString()));
            obj.setId(Integer.parseInt(txtcodigo.getText()));
            
            dao = new CidadesDAO();
            dao.alterarCidade(obj);
            
            JOptionPane.showMessageDialog(null,"Dados alterados com sucesso");
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao alterar a cidade");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }

}
