/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import dao.AlunosDAO;
import dao.DisciplinasDAO;
import dao.ProfessoresDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javabeans.Disciplinas;
import javabeans.Professores;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte
 */
public class Disciplina extends javax.swing.JDialog {
    DisciplinasDAO dao;
    /**
     * Creates new form Cidade
     */
    public Disciplina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public Disciplina(Disciplinas obj){
        initComponents();
        txtcodigo.setText(String.valueOf(obj.getId()));
        txtnome.setText(obj.getNome());
        txtdescricao.setText(obj.getDescricao());
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Disciplina dialog = new Disciplina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtprof = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        btnovo = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeladisciplina = new javax.swing.JTable();
        btatualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btbuscar = new javax.swing.JButton();
        txtnomebusca = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        btremover = new javax.swing.JButton();
        cboprof = new javax.swing.JComboBox<>();

        txtprof.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Disciplina");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtcodigo.setEditable(false);
        txtcodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        txtnome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        tabeladisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Descrição", "Codigo Prof"
            }
        ));
        tabeladisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeladisciplinaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeladisciplina);

        btatualizar.setText("Atualizar");
        btatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btatualizarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        btbuscar.setText("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        txtnomebusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        txtnomebusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomebuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtnomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnomebusca)
                    .addComponent(btbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtdescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        btremover.setText("Remover");
        btremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btremoverActionPerformed(evt);
            }
        });

        cboprof.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um professor" }));
        cboprof.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboprofItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btsalvar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btatualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btremover))))
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnovo)
                            .addComponent(btsalvar))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btatualizar)
                            .addComponent(btremover))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        Novo();
    }//GEN-LAST:event_btnovoActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        Salvar();
    }//GEN-LAST:event_btsalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
        
    }//GEN-LAST:event_formWindowActivated

    private void tabeladisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeladisciplinaMouseClicked
        txtcodigo.setText(tabeladisciplina.getValueAt(tabeladisciplina.getSelectedRow(),0).toString());
        txtnome.setText(tabeladisciplina.getValueAt(tabeladisciplina.getSelectedRow(),1).toString());
        txtdescricao.setText(tabeladisciplina.getValueAt(tabeladisciplina.getSelectedRow(),2).toString());
        DisciplinasDAO disciplina = new DisciplinasDAO();
        try{
            ProfessoresDAO dao_t = new ProfessoresDAO();
            List<Professores> lista = dao_t.listarProfessores();
            
            for(Professores u:lista){
                
                if(u.getId() == Integer.parseInt(tabeladisciplina.getValueAt(tabeladisciplina.getSelectedRow(),3).toString()))
                {    cboprof.setSelectedItem(u.getNome());break;}
            }
        }catch(Exception e){

        }
    }//GEN-LAST:event_tabeladisciplinaMouseClicked

    private void btatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btatualizarActionPerformed
        Atualizar();
    }//GEN-LAST:event_btatualizarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_btbuscarActionPerformed

    private void txtnomebuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomebuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomebuscaActionPerformed

    private void btremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btremoverActionPerformed
        Remover();
    }//GEN-LAST:event_btremoverActionPerformed

    private void cboprofItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboprofItemStateChanged
        if(cboprof.getSelectedItem().toString() != cboprof.getItemAt(0)){
            DisciplinasDAO disciplina = new DisciplinasDAO();
            try{
                
                txtprof.setText(String.valueOf(disciplina.getProfessor(cboprof.getSelectedItem().toString())));
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_cboprofItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            
            ProfessoresDAO dao_t = new ProfessoresDAO();
            List<Professores> lista = dao_t.listarProfessores();
            for(Professores u:lista){
                cboprof.addItem(u.getNome());
            }
                    
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btatualizar;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btremover;
    private javax.swing.JButton btsalvar;
    private javax.swing.JComboBox<String> cboprof;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabeladisciplina;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnomebusca;
    private javax.swing.JTextField txtprof;
    // End of variables declaration//GEN-END:variables

    void Novo(){
        txtcodigo.setText(null);
        txtnome.setText(null);
        txtdescricao.setText(null);
        txtnome.requestFocus();
    }
    void Remover(){
        try{
            
            Disciplinas obj = new Disciplinas();
            obj.setId(Integer.parseInt(txtcodigo.getText()));
            dao = new DisciplinasDAO();
            dao.removerDisciplina(obj);
            
            JOptionPane.showMessageDialog(null,"Operação feita realizado com sucesso");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro na operação ");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Salvar(){
        try{
            
            Disciplinas obj = new Disciplinas();
            obj.setNome(txtnome.getText());
            obj.setDescricao(txtdescricao.getText());
            obj.setPid(Integer.parseInt(txtprof.getText()));
            dao = new DisciplinasDAO();
            dao.cadastrarDisciplina(obj);
            
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar ");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Listar(){
        try{
            DisciplinasDAO dao = new DisciplinasDAO();
            List<Disciplinas> listaralunos = dao.listarDisciplinas();
            DefaultTableModel modelo = (DefaultTableModel) tabeladisciplina.getModel();
            modelo.setNumRows(0);
            
            for(Disciplinas lc : listaralunos){
                modelo.addRow(new Object[]{
                        lc.getId(),
                        lc.getNome(),
                        lc.getDescricao(),
                        lc.getPid()
                        });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    void Atualizar(){
        try{
            Disciplinas obj = new Disciplinas();
            obj.setId(Integer.parseInt(txtcodigo.getText()));
            obj.setNome(txtnome.getText());
            obj.setDescricao(txtdescricao.getText());
            obj.setPid(Integer.parseInt(txtprof.getText()));
            
            dao = new DisciplinasDAO();
            dao.alterarDisciplina(obj);
            JOptionPane.showMessageDialog(null,"Dados alterados com sucesso");
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao alterar");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Buscar(){
        try{
            DisciplinasDAO dao = new DisciplinasDAO();
            List<Disciplinas> listarclientes = dao.listarDisciplinasPorNome(txtnomebusca.getText());
            DefaultTableModel modelo = (DefaultTableModel) tabeladisciplina.getModel();
            modelo.setNumRows(0);
            
            for(Disciplinas lc : listarclientes){
                txtcodigo.setText(String.valueOf((lc.getId())));
                txtnome.setText(lc.getNome());
                txtdescricao.setText(lc.getDescricao());
                txtprof.setText(String.valueOf(lc.getPid()));
                modelo.addRow(new Object[]{
                        lc.getId(),
                        lc.getNome(),
                        lc.getDescricao(),
                        lc.getPid()
                        });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
}
