/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import dao.ProfessoresDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javabeans.Professores;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte
 */
public class Professor extends javax.swing.JDialog {
    ProfessoresDAO dao;
    /**
     * Creates new form Cidade
     */
    public Professor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public Professor(Professores obj){
        initComponents();
        txtcodigo.setText(String.valueOf(obj.getId()));
        txtnome.setText(obj.getNome());
        txtemail1.setText(obj.getEmail());
        txttelefone.setText(obj.getTelefone());
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Professor dialog = new Professor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcodigo = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        btnovo = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaalunos = new javax.swing.JTable();
        btatualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btbuscar = new javax.swing.JButton();
        txtnomebusca = new javax.swing.JTextField();
        txtemail1 = new javax.swing.JTextField();
        txttelefone = new javax.swing.JFormattedTextField();
        btremover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Professor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtcodigo.setEditable(false);
        txtcodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        txtnome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        tabelaalunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Email", "Telefone"
            }
        ));
        tabelaalunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaalunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaalunos);

        btatualizar.setText("Atualizar");
        btatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btatualizarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta"));

        btbuscar.setText("Buscar");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        txtnomebusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        txtnomebusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomebuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtnomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnomebusca)
                    .addComponent(btbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtemail1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txttelefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));
        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btremover.setText("Remover");
        btremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btsalvar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btatualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btremover))))
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnovo)
                            .addComponent(btsalvar))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btatualizar)
                            .addComponent(btremover))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txtemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        Novo();
    }//GEN-LAST:event_btnovoActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        Salvar();
    }//GEN-LAST:event_btsalvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaalunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaalunosMouseClicked
        txtcodigo.setText(tabelaalunos.getValueAt(tabelaalunos.getSelectedRow(),0).toString());
        txtnome.setText(tabelaalunos.getValueAt(tabelaalunos.getSelectedRow(),1).toString());
        txtemail1.setText(tabelaalunos.getValueAt(tabelaalunos.getSelectedRow(),2).toString());
        txttelefone.setText(tabelaalunos.getValueAt(tabelaalunos.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelaalunosMouseClicked

    private void btatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btatualizarActionPerformed
        Atualizar();
    }//GEN-LAST:event_btatualizarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        Buscar();
    }//GEN-LAST:event_btbuscarActionPerformed

    private void txtnomebuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomebuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomebuscaActionPerformed

    private void btremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btremoverActionPerformed
        Remover();
    }//GEN-LAST:event_btremoverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btatualizar;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btremover;
    private javax.swing.JButton btsalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaalunos;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnomebusca;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables

    void Novo(){
        txtcodigo.setText(null);
        txtnome.setText(null);
        txtemail1.setText(null);
        txttelefone.setText(null);
        txtnome.requestFocus();
    }
    void Remover(){
        try{
            
            Professores obj = new Professores();
            obj.setId(Integer.parseInt(txtcodigo.getText()));
            dao = new ProfessoresDAO();
            dao.removerProfessor(obj);
            
            JOptionPane.showMessageDialog(null,"Operação feita realizado com sucesso");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro na operação ");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Salvar(){
        try{
            
            Professores obj = new Professores();
            obj.setNome(txtnome.getText());
            obj.setEmail(txtemail1.getText());
            obj.setTelefone(txttelefone.getText());
            dao = new ProfessoresDAO();
            dao.cadastrarProfessor(obj);
            
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao cadastrar ");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Listar(){
        try{
            ProfessoresDAO dao = new ProfessoresDAO();
            List<Professores> listaralunos = dao.listarProfessores();
            DefaultTableModel modelo = (DefaultTableModel) tabelaalunos.getModel();
            modelo.setNumRows(0);
            
            for(Professores lc : listaralunos){
                modelo.addRow(new Object[]{
                        lc.getId(),
                        lc.getNome(),
                        lc.getEmail(),
                        lc.getTelefone()
                        });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    void Atualizar(){
        try{
            Professores obj = new Professores();
            obj.setId(Integer.parseInt(txtcodigo.getText()));
            obj.setNome(txtnome.getText());
            obj.setEmail(txtemail1.getText());
            obj.setTelefone(txttelefone.getText());
            
            dao = new ProfessoresDAO();
            dao.alterarProfessor(obj);
            JOptionPane.showMessageDialog(null,"Dados alterados com sucesso");
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao alterar");
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }
    void Buscar(){
        try{
            ProfessoresDAO dao = new ProfessoresDAO();
            List<Professores> listarclientes = dao.listarProfessoresPorNome(txtnomebusca.getText());
            DefaultTableModel modelo = (DefaultTableModel) tabelaalunos.getModel();
            modelo.setNumRows(0);
            
            for(Professores lc : listarclientes){
                txtcodigo.setText(String.valueOf((lc.getId())));
                txtnome.setText(lc.getNome());
                txtemail1.setText(lc.getEmail());
                txttelefone.setText(lc.getTelefone());
                modelo.addRow(new Object[]{
                        lc.getId(),
                        lc.getNome(),
                        lc.getEmail(),
                        lc.getTelefone()
                        });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
}
