/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import dao.AlunosDAO;
import dao.UsuarioDAO;
import javabeans.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Suporte
 */
public class TeladeLogin extends javax.swing.JDialog {

    /**
     * Creates new form TeladeLogin
     */
    public TeladeLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(570,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btlogar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setSize(400,600);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Tela de Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(123, 50, 286, 58);

        lblemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblemail.setText("E-mail:");
        getContentPane().add(lblemail);
        lblemail.setBounds(37, 149, 55, 22);

        lblsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblsenha.setText("Senha:");
        getContentPane().add(lblsenha);
        lblsenha.setBounds(38, 190, 54, 22);
        getContentPane().add(txtemail);
        txtemail.setBounds(124, 143, 339, 30);

        btlogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btlogar.setText("Logar");
        btlogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogarActionPerformed(evt);
            }
        });
        getContentPane().add(btlogar);
        btlogar.setBounds(220, 230, 103, 31);
        getContentPane().add(txtsenha);
        txtsenha.setBounds(124, 184, 339, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogoCEFET_formato-JPG.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 10, 484, 314);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogarActionPerformed
        // TODO add your handling code here:
        try{
            
            String email, senha;
            
            email = txtemail.getText();
            senha = new String(txtsenha.getPassword()).trim();
            UsuarioDAO dao = new UsuarioDAO();
            System.out.println(dao.efetuarLogin(email, senha));
            if(dao.efetuarLogin(email, senha)){
                Principal telacliente = new Principal ();
                this.dispose();    
                telacliente.setVisible(true);
                 
            }
            else{
                JOptionPane.showMessageDialog(null,"Dados incorretos");
            }
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_btlogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TeladeLogin dialog = new TeladeLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
